name: Deploy site to production bucket

on:
  push:
    branches:
      - master
      
permissions:
  id-token: write 
  contents: read  

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: janna-gha-example-prod
      AWS_REGION: us-east-1
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: actions/configure-aws-credentials@v1
        with:
         role-to-assume: arn:aws:iam::485758492827:role/janna-oidc-deployment
         role-session-name: StaticSiteDeployment
         aws-region: ${{ env.AWS_REGION }}
      - name: deploy files to bucket
        run: aws s3 cp public s3://${{ env.BUCKET_NAME }} --recursive --acl public-read
